---
title: "HW1"
author: "Erik Andersen"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE)
```


```{r}
# Load packages
pacman::p_load(tidyverse, here, haven, magrittr)

# Load data
burk_df = read_dta(here("HW1", "data", "burkina731.dta"))

# Change appropriate variables to factors
burk_df %<>% mutate(village = as.factor(village),
                    year = as.factor(year),
                    fcrop = as.factor(fcrop),
                    hhn = as.factor(hhn),
                    hhn_unique = hhn:village)

```


### Question 4

```{r}
# We're doing this cumbersome method to put the formula in because I thought it was cool, but mostly because I'm lazy and didn't wanna type out all the control variables

# Get vector of all control variables for ease of use
x = c(grep('soil', names(burk_df), value = TRUE), grep('topo', names(burk_df), value = TRUE), grep('loc', names(burk_df), value = TRUE), "lnarea")

# Add village fixed effects
village = c(x, "village*year*fcrop")

# Function that outputs regression formula
formula_generator = function(y = "lnvalue", x){
  a = paste(y, "~", sep = " ")
  paste(a, paste(paste0(x),  collapse = " + ")) |> as.formula()
}

# Village fixed effects formula
village_formula = formula_generator('lnvalue', village)
# Estimate first regression. 
village_reg = lm(village_formula, burk_df)
```


```{r}
# Now add household fixed effects
household = c(x, "hhn*year*fcrop")

# Formula
household_formula = formula_generator('lnvalue', household)
# Regression
household_reg = lm(household_formula, data = burk_df)
```

```{r}
# Graph the density of residuals from each regression
resids = tibble(village = village_reg$residuals, household = household_reg$residuals)

# Graph residuals
resids |> 
  ggplot(aes(village)) +
  geom_density(col = 'red') +
  geom_density(aes(x = household), col = 'blue') + 
  xlab("Deviation from Predicted Yield") +  ylab("Kernel Density Estimate") +
  ggtitle("Estimates of Yield Function Error Terms") + 
  cowplot::theme_cowplot()

# Test if distributions are different using KS test
with(resids, ks.test(village, household)) # Reject
```

### Question 5

```{r}
# Add log of hh size of other plots to data
hhsize = c("lnhhsize", x, "village*year*fcrop")

# Formula
hhsize_formula = formula_generator('lnvalue', hhsize)
# Run regression
other_reg = lm(hhsize_formula, burk_df)
summary(other_reg)
```













































